### ISSUE TITLE
Check whether to exist the x86_64-elf file in `$HOME/osbook/devenv`

### ISSUE THREAD

**Issue by ninokin25** [nino-kin/mikanos-build#6]
## Overview

Currently, if we run without the x86_64-elf file in `$HOME/osbook/devenv`, error is occurred.
So, we would like to download `x86_64-elf.tar.gz` and uncompress it automatically.

## Tasks

- [ ] Download the `x86_64-elf.tar.gz` file with CUI. (e.g. `curl`,  `wget`, etc)
- [ ] Uncompress the `x86_64-elf.tar.gz` file beneath `$HOME/osbook/devenv`.
- [ ] Run build command & check the test will be passed.
